### PR TITLE
all: remove obsolete build tags

### PR DESCRIPTION
**Pull request by alexandear**
This PR removes all `// +build` comments because they have been obsolete since Go 1.17. From the [doc](https://pkg.go.dev/cmd/go#hdr-Build_constraints):

> Go versions 1.16 and earlier used a different syntax for build constraints, with a "// +build" prefix. The gofmt command will add an equivalent //go:build constraint when encountering the older syntax.

### CODE REVIEW

**Comment by aarzilli** [comment]
What's the minimum version that we still actually build with?

**Comment by alexandear** [comment]
The minimum supported version is Go 1.17 as stated in the `go.mod`.

I got errors when trying to build with Go 1.16:
```
# golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/syscall.go:83:16: undefined: unsafe.Slice
vendor/golang.org/x/sys/unix/syscall_bsd.go:248:20: undefined: unsafe.Slice
vendor/golang.org/x/sys/unix/syscall_darwin.go:94:8: undefined: unsafe.Slice
vendor/golang.org/x/sys/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
vendor/golang.org/x/sys/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
make: *** [build] Error 1
```

**Comment by aarzilli** [comment]
Ah yes, it's because of the cilium update to fix the bug. Ok, LGTM, but we wanted to freeze for a week before releasing 1.21.1, so it will have to wait.
