### ISSUE TITLE
Can't build v1.4.1 with Go 1.11 anymore due to use of strings.ReplaceAll()

### ISSUE THREAD

**Issue by antiphp** [go-delve/delve#2077]
Hey,

Issue #2018 / v1.4.1 introduced the use of `strings.ReplaceAll` so `go install`  with Go 1.11 is not working anymore:
https://github.com/go-delve/delve/blame/708eadd5538edd222d8553b08b47c295474f38fa/pkg/proc/native/proc_linux.go#L170
```
# github.com/go-delve/delve/pkg/proc/native
../go/pkg/mod/github.com/go-delve/delve@v1.4.1/pkg/proc/native/proc_linux.go:170:16: undefined: strings.ReplaceAll
```

Since it's not really necessary to break it, especially in a bugfix version, I'd suggest to not use `strings.ReplaceAll()`.

**Comment by chainhelen** [comment]
duplicate #2067  

We only test and support the three most recent versions of Go. Use a more recent version of Go or a less recent version of Delve.

**Comment by antiphp** [comment]
I generally agree with this policy - there must be a cut somewhere. But I would have hoped for a better reason than just a convenience string function that could have been avoided pretty easily and (more important) introducing that in a patch version. How could someone know that this version is breaking and this one is not. Maybe one could pin a delve version to a set of Go versions... Anyways thanks for pointing it out.

**Comment by aarzilli** [comment]
@antiphp it is indeed unfortunate that this happened. If there was a way to test that we are not using API that are too new (without running tests on a much larger test matrix) I'd be for it. 

> How could someone know that this version is breaking and this one is not.

As it stands release 1.x.0 of delve will be tested against go 1.1x, 1.1(x-1) and 1.1(x-2), so 1.4.0 is guaranteed to build on 1.14, 1.13 and 1.12, but it could also accidentally build and work with older versions of Go.
